### PR TITLE
Replace DompdfWrapperInterface::streamHtml with DompdfWrapperInterface::getStreamResponse

### PR DESCRIPTION
**Pull request by julienlegrand07**
https://github.com/nucleos/NucleosDompdfBundle/issues/171

Closes #{171}

## Subject

Fixed phpstan error message : 
Call to an undefined method Nucleos\DompdfBundle\Wrapper\DompdfWrapperInterface::getStreamResponse().

### CODE REVIEW

**Comment by core23** [comment]
Thanks for your PR. This is a major change, because you added a new method to the interface. 

Can you please remove the deprecated method too

**Comment by julienlegrand07** [comment]
> Thanks for your PR. This is a major change, because you added a new method to the interface.
> 
> Can you please remove the deprecated method too

done

**Review by core23 — APPROVED** [review]

**Comment by julienlegrand07** [comment]
Hello @core23 

Are there still concerns to move forward?
Can I do something?

**Comment by core23** [comment]
> Hello @core23
> 
> Are there still concerns to move forward?
> Can I do something?

It's fine, you just need to wait.

I only have one active development branch (and don't want to maintain more). Merging this PR will result in a major release which I don't want for now.

**Pull request merged**
